# Conda environment to enable code checking in vscode.
# Create using `./conda-env-create.sh` to handle dependencies correctly.
name: groundscale
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
