[pytest]
pythonpath = src
addopts = --basetemp=./tests/results/ --cov-report=lcov -v --capture=tee-sys --cov-append
markers =
    long: marks tests as long (deselect with '-m "not long"')
    gpu: marks tests that require a GPU (deselect with '-m "not gpu"' or '-m "not gpu(multi=True)"')
