[pytest]
pythonpath = src
testpaths = tests
addopts = --basetemp=./tests/results/ --cov-report=lcov -v --capture=tee-sys --cov-append -m "not upstream"
markers =
    long: marks tests as long (deselect with '-m "not long"')
    gpu: marks tests that require a GPU (deselect with '-m "not gpu"' or '-m "not gpu(multi=True)"')
    upstream: marks the upstream implementation comparison (deselect with '-m "not upstream"')
