name: Docs
on:
  pull_request:
    types: [closed]
    branches:
      - master
    paths:
      - docs/**
      - src/**
      - docker/Dockerfile
      - requirements*.txt
  workflow_dispatch:
permissions:
    contents: write
jobs:
  docs:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Build documentation image
        run: |
          docker build \
            --target docs \
            --tag groundgan-docs \
            --file docker/Dockerfile .

      - name: Sphinx build
        run: |
          docker run --rm \
            --volume "${GITHUB_WORKSPACE}/docs:/groundgan/docs" \
            groundgan-docs \
            -b html \
            /groundgan/docs \
            /groundgan/docs/_build/html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true
